//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financiera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Solicitudes = new HashSet<Solicitudes>();
            this.Solicitudes1 = new HashSet<Solicitudes>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string dni { get; set; }
        public string domicilio { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estadoCivil { get; set; }
        public string localidad { get; set; }
        public Nullable<int> codigoPostal { get; set; }
        public string observaciones { get; set; }
        public string empresa { get; set; }
        public string cargo { get; set; }
        public string cuit { get; set; }
        public string domicilioEmpresa { get; set; }
        public string localidadEmpresa { get; set; }
        public string codigoPostalEmpresa { get; set; }
        public Nullable<decimal> ingresos { get; set; }
        public Nullable<int> antiguedad { get; set; }
        public string madre { get; set; }
        public string padre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes> Solicitudes1 { get; set; }
    }
}
