//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financiera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observaciones
    {
        public int id { get; set; }
        public string observacion { get; set; }
        public Nullable<int> idTipoObservacion { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idSolicitud { get; set; }
    
        public virtual Solicitudes Solicitudes { get; set; }
        public virtual TiposObservaciones TiposObservaciones { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
