//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financiera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudBancos
    {
        public int id { get; set; }
        public Nullable<int> idSolicitud { get; set; }
        public Nullable<int> idEntidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> TNA { get; set; }
        public string Observaciones { get; set; }
        public string CodigoSeguimiento { get; set; }
    
        public virtual Entidades Entidades { get; set; }
        public virtual Solicitudes Solicitudes { get; set; }
    }
}
