//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financiera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitudes()
        {
            this.Observaciones1 = new HashSet<Observaciones>();
            this.SolicitudBancos = new HashSet<SolicitudBancos>();
        }
    
        public int id { get; set; }
        public int idCliente { get; set; }
        public Nullable<int> idConyuge { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idVendedor { get; set; }
        public Nullable<int> idEntidad { get; set; }
        public Nullable<int> idRechazo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string codigoEntidad { get; set; }
        public bool entregaGestor { get; set; }
        public Nullable<System.DateTime> fechaEntregaGestor { get; set; }
        public Nullable<System.DateTime> fechaDevolucionPrenda { get; set; }
        public bool prendaInscripta { get; set; }
        public Nullable<System.DateTime> fechaInscripcionPrenda { get; set; }
        public Nullable<System.DateTime> fechaUltimoPago { get; set; }
        public Nullable<System.DateTime> fechaFirma { get; set; }
        public Nullable<System.DateTime> fechaNuevaLlamada { get; set; }
        public Nullable<int> Cuotas { get; set; }
        public string Vehiculo { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Clientes Clientes1 { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual Estados Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observaciones> Observaciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudBancos> SolicitudBancos { get; set; }
        public virtual TiposRechazos TiposRechazos { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual Vendedores Vendedores { get; set; }
    }
}
